apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: hello-world
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: hello-world
            port:
              number: 8089
        path: /
        pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  ports:
  - port: 8089
  selector:
    app: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    ressources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
    spec:
      containers:
      - image: nginx:stable
        name: nginx
        ports:
        - containerPort: 8089
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: hello-world-volume
    volumes:
    - configMap:
        name: hello-world-configmap
      name: hello-world-volume
