# Use an official Nginx runtime as a parent image
FROM nginx:stable

# Creating path if it does not exist
RUN mkdir -p /usr/share/nginx/html

# going to the html page
WORKDIR /usr/share/nginx/html

# Removing current welcome file
RUN rm -vf index*

# Copy the "Hello, World!" HTML file into the Nginx docker
COPY index.html .

# Going back to the root
WORKDIR /

# Expose port 80 for HTTP
EXPOSE 80

# Command to start Nginx
CMD ["nginx", "-g", "daemon off;"]
